name: VPS Free (Windows Ubuntu Latest)

on:
  schedule:
    - cron: '0 */5 * * *'  # Executar a cada 5 horas 
  workflow_dispatch:

jobs:
  criar-maquina:
    runs-on: windows-latest

    steps:
    - name: Criar Nova MÃ¡quina
      run: |
        choco install ngrok
        ngrok config add-authtoken 2dEyxB5ml6BSMTSE2IFuVfH5XAm_5jeqegdgEtwXWVuygVKKx
        net user golden Jurtg@(3456 /add
        net localgroup Administrators golden /add
        & ngrok http --domain=wildcat-wealthy-chicken.ngrok-free.app 4040
        ngrok tcp 3389
